# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Brett Yukich
tagline:          An OK guy
url:              http://brettyukich.co.nz
paginate:         1
baseurl:          http://brettyukich.co.nz/
author:
  name:           Brett Yukich
  url:            http://brettyukich.co.nz
  email:          brett@yukich.co.nz

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/brettanomyces/poole
